// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	outports "github.com/llascola/web-backend/internal/app/outports"
)

// MockFileStorageRepository is an autogenerated mock type for the FileStorageRepository type
type MockFileStorageRepository struct {
	mock.Mock
}

type MockFileStorageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileStorageRepository) EXPECT() *MockFileStorageRepository_Expecter {
	return &MockFileStorageRepository_Expecter{mock: &_m.Mock}
}

// Save provides a mock function with given fields: ctx, file, meta
func (_m *MockFileStorageRepository) Save(ctx context.Context, file io.Reader, meta outports.FileMetadata) (string, error) {
	ret := _m.Called(ctx, file, meta)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, outports.FileMetadata) (string, error)); ok {
		return rf(ctx, file, meta)
	}
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, outports.FileMetadata) string); ok {
		r0 = rf(ctx, file, meta)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, io.Reader, outports.FileMetadata) error); ok {
		r1 = rf(ctx, file, meta)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileStorageRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockFileStorageRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - file io.Reader
//   - meta outports.FileMetadata
func (_e *MockFileStorageRepository_Expecter) Save(ctx interface{}, file interface{}, meta interface{}) *MockFileStorageRepository_Save_Call {
	return &MockFileStorageRepository_Save_Call{Call: _e.mock.On("Save", ctx, file, meta)}
}

func (_c *MockFileStorageRepository_Save_Call) Run(run func(ctx context.Context, file io.Reader, meta outports.FileMetadata)) *MockFileStorageRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Reader), args[2].(outports.FileMetadata))
	})
	return _c
}

func (_c *MockFileStorageRepository_Save_Call) Return(_a0 string, _a1 error) *MockFileStorageRepository_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileStorageRepository_Save_Call) RunAndReturn(run func(context.Context, io.Reader, outports.FileMetadata) (string, error)) *MockFileStorageRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileStorageRepository creates a new instance of MockFileStorageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileStorageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileStorageRepository {
	mock := &MockFileStorageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
