// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockTokenBlocklist is an autogenerated mock type for the TokenBlocklist type
type MockTokenBlocklist struct {
	mock.Mock
}

type MockTokenBlocklist_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenBlocklist) EXPECT() *MockTokenBlocklist_Expecter {
	return &MockTokenBlocklist_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, jti, expiration
func (_m *MockTokenBlocklist) Add(ctx context.Context, jti string, expiration time.Time) error {
	ret := _m.Called(ctx, jti, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, jti, expiration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenBlocklist_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockTokenBlocklist_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
//   - expiration time.Time
func (_e *MockTokenBlocklist_Expecter) Add(ctx interface{}, jti interface{}, expiration interface{}) *MockTokenBlocklist_Add_Call {
	return &MockTokenBlocklist_Add_Call{Call: _e.mock.On("Add", ctx, jti, expiration)}
}

func (_c *MockTokenBlocklist_Add_Call) Run(run func(ctx context.Context, jti string, expiration time.Time)) *MockTokenBlocklist_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockTokenBlocklist_Add_Call) Return(_a0 error) *MockTokenBlocklist_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenBlocklist_Add_Call) RunAndReturn(run func(context.Context, string, time.Time) error) *MockTokenBlocklist_Add_Call {
	_c.Call.Return(run)
	return _c
}

// IsBlocked provides a mock function with given fields: ctx, jti
func (_m *MockTokenBlocklist) IsBlocked(ctx context.Context, jti string) (bool, error) {
	ret := _m.Called(ctx, jti)

	if len(ret) == 0 {
		panic("no return value specified for IsBlocked")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, jti)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, jti)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jti)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenBlocklist_IsBlocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBlocked'
type MockTokenBlocklist_IsBlocked_Call struct {
	*mock.Call
}

// IsBlocked is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
func (_e *MockTokenBlocklist_Expecter) IsBlocked(ctx interface{}, jti interface{}) *MockTokenBlocklist_IsBlocked_Call {
	return &MockTokenBlocklist_IsBlocked_Call{Call: _e.mock.On("IsBlocked", ctx, jti)}
}

func (_c *MockTokenBlocklist_IsBlocked_Call) Run(run func(ctx context.Context, jti string)) *MockTokenBlocklist_IsBlocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenBlocklist_IsBlocked_Call) Return(_a0 bool, _a1 error) *MockTokenBlocklist_IsBlocked_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenBlocklist_IsBlocked_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockTokenBlocklist_IsBlocked_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenBlocklist creates a new instance of MockTokenBlocklist. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenBlocklist(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenBlocklist {
	mock := &MockTokenBlocklist{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
