// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/llascola/web-backend/internal/adapters/driven/repository/ent/blogpost"
	"github.com/llascola/web-backend/internal/adapters/driven/repository/ent/predicate"
	"github.com/llascola/web-backend/internal/adapters/driven/repository/ent/tag"
)

// BlogPostUpdate is the builder for updating BlogPost entities.
type BlogPostUpdate struct {
	config
	hooks    []Hook
	mutation *BlogPostMutation
}

// Where appends a list predicates to the BlogPostUpdate builder.
func (_u *BlogPostUpdate) Where(ps ...predicate.BlogPost) *BlogPostUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *BlogPostUpdate) SetTitle(v string) *BlogPostUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BlogPostUpdate) SetNillableTitle(v *string) *BlogPostUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *BlogPostUpdate) SetSlug(v string) *BlogPostUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *BlogPostUpdate) SetNillableSlug(v *string) *BlogPostUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *BlogPostUpdate) SetContent(v string) *BlogPostUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *BlogPostUpdate) SetNillableContent(v *string) *BlogPostUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetExcerpt sets the "excerpt" field.
func (_u *BlogPostUpdate) SetExcerpt(v string) *BlogPostUpdate {
	_u.mutation.SetExcerpt(v)
	return _u
}

// SetNillableExcerpt sets the "excerpt" field if the given value is not nil.
func (_u *BlogPostUpdate) SetNillableExcerpt(v *string) *BlogPostUpdate {
	if v != nil {
		_u.SetExcerpt(*v)
	}
	return _u
}

// ClearExcerpt clears the value of the "excerpt" field.
func (_u *BlogPostUpdate) ClearExcerpt() *BlogPostUpdate {
	_u.mutation.ClearExcerpt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *BlogPostUpdate) SetStatus(v blogpost.Status) *BlogPostUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BlogPostUpdate) SetNillableStatus(v *blogpost.Status) *BlogPostUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *BlogPostUpdate) SetAuthorID(v uuid.UUID) *BlogPostUpdate {
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *BlogPostUpdate) SetNillableAuthorID(v *uuid.UUID) *BlogPostUpdate {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *BlogPostUpdate) SetCreatedAt(v time.Time) *BlogPostUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *BlogPostUpdate) SetNillableCreatedAt(v *time.Time) *BlogPostUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BlogPostUpdate) SetUpdatedAt(v time.Time) *BlogPostUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *BlogPostUpdate) SetPublishedAt(v time.Time) *BlogPostUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *BlogPostUpdate) SetNillablePublishedAt(v *time.Time) *BlogPostUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *BlogPostUpdate) ClearPublishedAt() *BlogPostUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_u *BlogPostUpdate) AddTagIDs(ids ...uuid.UUID) *BlogPostUpdate {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *BlogPostUpdate) AddTags(v ...*Tag) *BlogPostUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// Mutation returns the BlogPostMutation object of the builder.
func (_u *BlogPostUpdate) Mutation() *BlogPostMutation {
	return _u.mutation
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *BlogPostUpdate) ClearTags() *BlogPostUpdate {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (_u *BlogPostUpdate) RemoveTagIDs(ids ...uuid.UUID) *BlogPostUpdate {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *BlogPostUpdate) RemoveTags(v ...*Tag) *BlogPostUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BlogPostUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BlogPostUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BlogPostUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BlogPostUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BlogPostUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := blogpost.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BlogPostUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := blogpost.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "BlogPost.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := blogpost.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "BlogPost.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := blogpost.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "BlogPost.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := blogpost.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BlogPost.status": %w`, err)}
		}
	}
	return nil
}

func (_u *BlogPostUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(blogpost.Table, blogpost.Columns, sqlgraph.NewFieldSpec(blogpost.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(blogpost.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(blogpost.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(blogpost.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Excerpt(); ok {
		_spec.SetField(blogpost.FieldExcerpt, field.TypeString, value)
	}
	if _u.mutation.ExcerptCleared() {
		_spec.ClearField(blogpost.FieldExcerpt, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(blogpost.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AuthorID(); ok {
		_spec.SetField(blogpost.FieldAuthorID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(blogpost.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(blogpost.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(blogpost.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(blogpost.FieldPublishedAt, field.TypeTime)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   blogpost.TagsTable,
			Columns: blogpost.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   blogpost.TagsTable,
			Columns: blogpost.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   blogpost.TagsTable,
			Columns: blogpost.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blogpost.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BlogPostUpdateOne is the builder for updating a single BlogPost entity.
type BlogPostUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BlogPostMutation
}

// SetTitle sets the "title" field.
func (_u *BlogPostUpdateOne) SetTitle(v string) *BlogPostUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BlogPostUpdateOne) SetNillableTitle(v *string) *BlogPostUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *BlogPostUpdateOne) SetSlug(v string) *BlogPostUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *BlogPostUpdateOne) SetNillableSlug(v *string) *BlogPostUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *BlogPostUpdateOne) SetContent(v string) *BlogPostUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *BlogPostUpdateOne) SetNillableContent(v *string) *BlogPostUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetExcerpt sets the "excerpt" field.
func (_u *BlogPostUpdateOne) SetExcerpt(v string) *BlogPostUpdateOne {
	_u.mutation.SetExcerpt(v)
	return _u
}

// SetNillableExcerpt sets the "excerpt" field if the given value is not nil.
func (_u *BlogPostUpdateOne) SetNillableExcerpt(v *string) *BlogPostUpdateOne {
	if v != nil {
		_u.SetExcerpt(*v)
	}
	return _u
}

// ClearExcerpt clears the value of the "excerpt" field.
func (_u *BlogPostUpdateOne) ClearExcerpt() *BlogPostUpdateOne {
	_u.mutation.ClearExcerpt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *BlogPostUpdateOne) SetStatus(v blogpost.Status) *BlogPostUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BlogPostUpdateOne) SetNillableStatus(v *blogpost.Status) *BlogPostUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *BlogPostUpdateOne) SetAuthorID(v uuid.UUID) *BlogPostUpdateOne {
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *BlogPostUpdateOne) SetNillableAuthorID(v *uuid.UUID) *BlogPostUpdateOne {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *BlogPostUpdateOne) SetCreatedAt(v time.Time) *BlogPostUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *BlogPostUpdateOne) SetNillableCreatedAt(v *time.Time) *BlogPostUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BlogPostUpdateOne) SetUpdatedAt(v time.Time) *BlogPostUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *BlogPostUpdateOne) SetPublishedAt(v time.Time) *BlogPostUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *BlogPostUpdateOne) SetNillablePublishedAt(v *time.Time) *BlogPostUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *BlogPostUpdateOne) ClearPublishedAt() *BlogPostUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_u *BlogPostUpdateOne) AddTagIDs(ids ...uuid.UUID) *BlogPostUpdateOne {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *BlogPostUpdateOne) AddTags(v ...*Tag) *BlogPostUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// Mutation returns the BlogPostMutation object of the builder.
func (_u *BlogPostUpdateOne) Mutation() *BlogPostMutation {
	return _u.mutation
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *BlogPostUpdateOne) ClearTags() *BlogPostUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (_u *BlogPostUpdateOne) RemoveTagIDs(ids ...uuid.UUID) *BlogPostUpdateOne {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *BlogPostUpdateOne) RemoveTags(v ...*Tag) *BlogPostUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// Where appends a list predicates to the BlogPostUpdate builder.
func (_u *BlogPostUpdateOne) Where(ps ...predicate.BlogPost) *BlogPostUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BlogPostUpdateOne) Select(field string, fields ...string) *BlogPostUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BlogPost entity.
func (_u *BlogPostUpdateOne) Save(ctx context.Context) (*BlogPost, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BlogPostUpdateOne) SaveX(ctx context.Context) *BlogPost {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BlogPostUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BlogPostUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BlogPostUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := blogpost.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BlogPostUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := blogpost.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "BlogPost.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := blogpost.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "BlogPost.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := blogpost.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "BlogPost.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := blogpost.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BlogPost.status": %w`, err)}
		}
	}
	return nil
}

func (_u *BlogPostUpdateOne) sqlSave(ctx context.Context) (_node *BlogPost, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(blogpost.Table, blogpost.Columns, sqlgraph.NewFieldSpec(blogpost.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BlogPost.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, blogpost.FieldID)
		for _, f := range fields {
			if !blogpost.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != blogpost.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(blogpost.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(blogpost.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(blogpost.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Excerpt(); ok {
		_spec.SetField(blogpost.FieldExcerpt, field.TypeString, value)
	}
	if _u.mutation.ExcerptCleared() {
		_spec.ClearField(blogpost.FieldExcerpt, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(blogpost.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AuthorID(); ok {
		_spec.SetField(blogpost.FieldAuthorID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(blogpost.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(blogpost.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(blogpost.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(blogpost.FieldPublishedAt, field.TypeTime)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   blogpost.TagsTable,
			Columns: blogpost.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   blogpost.TagsTable,
			Columns: blogpost.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   blogpost.TagsTable,
			Columns: blogpost.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BlogPost{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blogpost.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
