// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/llascola/web-backend/internal/adapters/driven/repository/ent/blogpost"
	"github.com/llascola/web-backend/internal/adapters/driven/repository/ent/tag"
)

// BlogPostCreate is the builder for creating a BlogPost entity.
type BlogPostCreate struct {
	config
	mutation *BlogPostMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *BlogPostCreate) SetTitle(v string) *BlogPostCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *BlogPostCreate) SetSlug(v string) *BlogPostCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *BlogPostCreate) SetContent(v string) *BlogPostCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetExcerpt sets the "excerpt" field.
func (_c *BlogPostCreate) SetExcerpt(v string) *BlogPostCreate {
	_c.mutation.SetExcerpt(v)
	return _c
}

// SetNillableExcerpt sets the "excerpt" field if the given value is not nil.
func (_c *BlogPostCreate) SetNillableExcerpt(v *string) *BlogPostCreate {
	if v != nil {
		_c.SetExcerpt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *BlogPostCreate) SetStatus(v blogpost.Status) *BlogPostCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetAuthorID sets the "author_id" field.
func (_c *BlogPostCreate) SetAuthorID(v uuid.UUID) *BlogPostCreate {
	_c.mutation.SetAuthorID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BlogPostCreate) SetCreatedAt(v time.Time) *BlogPostCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BlogPostCreate) SetNillableCreatedAt(v *time.Time) *BlogPostCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BlogPostCreate) SetUpdatedAt(v time.Time) *BlogPostCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BlogPostCreate) SetNillableUpdatedAt(v *time.Time) *BlogPostCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *BlogPostCreate) SetPublishedAt(v time.Time) *BlogPostCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *BlogPostCreate) SetNillablePublishedAt(v *time.Time) *BlogPostCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BlogPostCreate) SetID(v uuid.UUID) *BlogPostCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *BlogPostCreate) SetNillableID(v *uuid.UUID) *BlogPostCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_c *BlogPostCreate) AddTagIDs(ids ...uuid.UUID) *BlogPostCreate {
	_c.mutation.AddTagIDs(ids...)
	return _c
}

// AddTags adds the "tags" edges to the Tag entity.
func (_c *BlogPostCreate) AddTags(v ...*Tag) *BlogPostCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTagIDs(ids...)
}

// Mutation returns the BlogPostMutation object of the builder.
func (_c *BlogPostCreate) Mutation() *BlogPostMutation {
	return _c.mutation
}

// Save creates the BlogPost in the database.
func (_c *BlogPostCreate) Save(ctx context.Context) (*BlogPost, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BlogPostCreate) SaveX(ctx context.Context) *BlogPost {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BlogPostCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BlogPostCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BlogPostCreate) defaults() {
	if _, ok := _c.mutation.Excerpt(); !ok {
		v := blogpost.DefaultExcerpt
		_c.mutation.SetExcerpt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := blogpost.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := blogpost.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := blogpost.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BlogPostCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "BlogPost.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := blogpost.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "BlogPost.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "BlogPost.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := blogpost.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "BlogPost.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "BlogPost.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := blogpost.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "BlogPost.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "BlogPost.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := blogpost.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BlogPost.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthorID(); !ok {
		return &ValidationError{Name: "author_id", err: errors.New(`ent: missing required field "BlogPost.author_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BlogPost.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BlogPost.updated_at"`)}
	}
	return nil
}

func (_c *BlogPostCreate) sqlSave(ctx context.Context) (*BlogPost, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BlogPostCreate) createSpec() (*BlogPost, *sqlgraph.CreateSpec) {
	var (
		_node = &BlogPost{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(blogpost.Table, sqlgraph.NewFieldSpec(blogpost.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(blogpost.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(blogpost.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(blogpost.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Excerpt(); ok {
		_spec.SetField(blogpost.FieldExcerpt, field.TypeString, value)
		_node.Excerpt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(blogpost.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AuthorID(); ok {
		_spec.SetField(blogpost.FieldAuthorID, field.TypeUUID, value)
		_node.AuthorID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(blogpost.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(blogpost.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(blogpost.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if nodes := _c.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   blogpost.TagsTable,
			Columns: blogpost.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BlogPostCreateBulk is the builder for creating many BlogPost entities in bulk.
type BlogPostCreateBulk struct {
	config
	err      error
	builders []*BlogPostCreate
}

// Save creates the BlogPost entities in the database.
func (_c *BlogPostCreateBulk) Save(ctx context.Context) ([]*BlogPost, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BlogPost, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BlogPostMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BlogPostCreateBulk) SaveX(ctx context.Context) []*BlogPost {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BlogPostCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BlogPostCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
